parser: "@typescript-eslint/parser"
env:
  es6: true
  browser: true
extends:
  - airbnb
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/react
plugins:
  - "@typescript-eslint"
  - import
  - react
  - react-hooks
  - prettier
settings:
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
rules:
  react/prop-types: off
  import/prefer-default-export: off
  no-undef: off
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
     - error
     - argsIgnorePattern: "^_"
  react-hooks/rules-of-hooks: error
  react/jsx-filename-extension:
    - error
    - extensions:
      - .js
      - .jsx
      - .ts
      - .tsx
  prettier/prettier:
    - error
    - trailingComma: none
      singleQuote: true
      semi: false
      bracketSpacing: true

